/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'
import type { CreateFileRoute, FileRoutesByPath } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalTerminosCondicionesRouteImport } from './routes/portal/terminos-condiciones'
import { Route as PortalPoliticasDePrivacidadRouteImport } from './routes/portal/politicas-de-privacidad'
import { Route as AuthenticatedLayoutRouteImport } from './routes/_authenticated/_layout'
import { Route as AuthenticatedLayoutMisDatosIndexRouteImport } from './routes/_authenticated/_layout/mis-datos/index'
import { Route as AuthenticatedLayoutPortalNotificacionesIndexRouteImport } from './routes/_authenticated/_layout/portal/notificaciones/index'
import { Route as AuthenticatedLayoutPortalDashboardIndexRouteImport } from './routes/_authenticated/_layout/portal/dashboard/index'

const AuthLayoutLazyRouteImport = createFileRoute('/_auth/_layout')()
const AuthLayoutVerifyEmailLazyRouteImport = createFileRoute(
  '/_auth/_layout/verify-email',
)()
const AuthLayoutRegistrarmeLazyRouteImport = createFileRoute(
  '/_auth/_layout/registrarme',
)()
const AuthLayoutRecuperarContrasenaLazyRouteImport = createFileRoute(
  '/_auth/_layout/recuperar-contrasena',
)()
const AuthLayoutIniciarSesionLazyRouteImport = createFileRoute(
  '/_auth/_layout/iniciar-sesion',
)()
const _emailEmailResendLazyRouteImport = createFileRoute(
  '/__email/email/resend',
)()
const AuthLayoutRecuperarContrasenaIndexLazyRouteImport = createFileRoute(
  '/_auth/_layout/recuperar-contrasena/',
)()
const AuthLayoutRecuperarContrasenaNuevaContrasenaLazyRouteImport =
  createFileRoute('/_auth/_layout/recuperar-contrasena/nueva-contrasena')()
const _emailEmailVerifyTokenLazyRouteImport = createFileRoute(
  '/__email/email/verify/$token',
)()

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutLazyRoute = AuthLayoutLazyRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth/_layout.lazy').then((d) => d.Route))
const PortalTerminosCondicionesRoute =
  PortalTerminosCondicionesRouteImport.update({
    id: '/portal/terminos-condiciones',
    path: '/portal/terminos-condiciones',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortalPoliticasDePrivacidadRoute =
  PortalPoliticasDePrivacidadRouteImport.update({
    id: '/portal/politicas-de-privacidad',
    path: '/portal/politicas-de-privacidad',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedLayoutRoute = AuthenticatedLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthLayoutVerifyEmailLazyRoute =
  AuthLayoutVerifyEmailLazyRouteImport.update({
    id: '/verify-email',
    path: '/verify-email',
    getParentRoute: () => AuthLayoutLazyRoute,
  } as any).lazy(() =>
    import('./routes/_auth/_layout/verify-email.lazy').then((d) => d.Route),
  )
const AuthLayoutRegistrarmeLazyRoute =
  AuthLayoutRegistrarmeLazyRouteImport.update({
    id: '/registrarme',
    path: '/registrarme',
    getParentRoute: () => AuthLayoutLazyRoute,
  } as any).lazy(() =>
    import('./routes/_auth/_layout/registrarme.lazy').then((d) => d.Route),
  )
const AuthLayoutRecuperarContrasenaLazyRoute =
  AuthLayoutRecuperarContrasenaLazyRouteImport.update({
    id: '/recuperar-contrasena',
    path: '/recuperar-contrasena',
    getParentRoute: () => AuthLayoutLazyRoute,
  } as any).lazy(() =>
    import('./routes/_auth/_layout/recuperar-contrasena.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthLayoutIniciarSesionLazyRoute =
  AuthLayoutIniciarSesionLazyRouteImport.update({
    id: '/iniciar-sesion',
    path: '/iniciar-sesion',
    getParentRoute: () => AuthLayoutLazyRoute,
  } as any).lazy(() =>
    import('./routes/_auth/_layout/iniciar-sesion.lazy').then((d) => d.Route),
  )
const _emailEmailResendLazyRoute = _emailEmailResendLazyRouteImport
  .update({
    id: '/__email/email/resend',
    path: '/email/resend',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/__email/email.resend.lazy').then((d) => d.Route))
const AuthLayoutRecuperarContrasenaIndexLazyRoute =
  AuthLayoutRecuperarContrasenaIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthLayoutRecuperarContrasenaLazyRoute,
  } as any).lazy(() =>
    import('./routes/_auth/_layout/recuperar-contrasena/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedLayoutMisDatosIndexRoute =
  AuthenticatedLayoutMisDatosIndexRouteImport.update({
    id: '/mis-datos/',
    path: '/mis-datos/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthLayoutRecuperarContrasenaNuevaContrasenaLazyRoute =
  AuthLayoutRecuperarContrasenaNuevaContrasenaLazyRouteImport.update({
    id: '/nueva-contrasena',
    path: '/nueva-contrasena',
    getParentRoute: () => AuthLayoutRecuperarContrasenaLazyRoute,
  } as any).lazy(() =>
    import('./routes/_auth/_layout/recuperar-contrasena/nueva-contrasena.lazy').then(
      (d) => d.Route,
    ),
  )
const _emailEmailVerifyTokenLazyRoute = _emailEmailVerifyTokenLazyRouteImport
  .update({
    id: '/__email/email/verify/$token',
    path: '/email/verify/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/__email/email.verify.$token.lazy').then((d) => d.Route),
  )
const AuthenticatedLayoutPortalNotificacionesIndexRoute =
  AuthenticatedLayoutPortalNotificacionesIndexRouteImport.update({
    id: '/portal/notificaciones/',
    path: '/portal/notificaciones/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutPortalDashboardIndexRoute =
  AuthenticatedLayoutPortalDashboardIndexRouteImport.update({
    id: '/portal/dashboard/',
    path: '/portal/dashboard/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/portal/politicas-de-privacidad': typeof PortalPoliticasDePrivacidadRoute
  '/portal/terminos-condiciones': typeof PortalTerminosCondicionesRoute
  '/email/resend': typeof _emailEmailResendLazyRoute
  '/iniciar-sesion': typeof AuthLayoutIniciarSesionLazyRoute
  '/recuperar-contrasena': typeof AuthLayoutRecuperarContrasenaLazyRouteWithChildren
  '/registrarme': typeof AuthLayoutRegistrarmeLazyRoute
  '/verify-email': typeof AuthLayoutVerifyEmailLazyRoute
  '/email/verify/$token': typeof _emailEmailVerifyTokenLazyRoute
  '/recuperar-contrasena/nueva-contrasena': typeof AuthLayoutRecuperarContrasenaNuevaContrasenaLazyRoute
  '/mis-datos/': typeof AuthenticatedLayoutMisDatosIndexRoute
  '/recuperar-contrasena/': typeof AuthLayoutRecuperarContrasenaIndexLazyRoute
  '/portal/dashboard/': typeof AuthenticatedLayoutPortalDashboardIndexRoute
  '/portal/notificaciones/': typeof AuthenticatedLayoutPortalNotificacionesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/portal/politicas-de-privacidad': typeof PortalPoliticasDePrivacidadRoute
  '/portal/terminos-condiciones': typeof PortalTerminosCondicionesRoute
  '/email/resend': typeof _emailEmailResendLazyRoute
  '/iniciar-sesion': typeof AuthLayoutIniciarSesionLazyRoute
  '/registrarme': typeof AuthLayoutRegistrarmeLazyRoute
  '/verify-email': typeof AuthLayoutVerifyEmailLazyRoute
  '/email/verify/$token': typeof _emailEmailVerifyTokenLazyRoute
  '/recuperar-contrasena/nueva-contrasena': typeof AuthLayoutRecuperarContrasenaNuevaContrasenaLazyRoute
  '/mis-datos': typeof AuthenticatedLayoutMisDatosIndexRoute
  '/recuperar-contrasena': typeof AuthLayoutRecuperarContrasenaIndexLazyRoute
  '/portal/dashboard': typeof AuthenticatedLayoutPortalDashboardIndexRoute
  '/portal/notificaciones': typeof AuthenticatedLayoutPortalNotificacionesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/_layout': typeof AuthenticatedLayoutRouteWithChildren
  '/portal/politicas-de-privacidad': typeof PortalPoliticasDePrivacidadRoute
  '/portal/terminos-condiciones': typeof PortalTerminosCondicionesRoute
  '/_auth/_layout': typeof AuthLayoutLazyRouteWithChildren
  '/__email/email/resend': typeof _emailEmailResendLazyRoute
  '/_auth/_layout/iniciar-sesion': typeof AuthLayoutIniciarSesionLazyRoute
  '/_auth/_layout/recuperar-contrasena': typeof AuthLayoutRecuperarContrasenaLazyRouteWithChildren
  '/_auth/_layout/registrarme': typeof AuthLayoutRegistrarmeLazyRoute
  '/_auth/_layout/verify-email': typeof AuthLayoutVerifyEmailLazyRoute
  '/__email/email/verify/$token': typeof _emailEmailVerifyTokenLazyRoute
  '/_auth/_layout/recuperar-contrasena/nueva-contrasena': typeof AuthLayoutRecuperarContrasenaNuevaContrasenaLazyRoute
  '/_authenticated/_layout/mis-datos/': typeof AuthenticatedLayoutMisDatosIndexRoute
  '/_auth/_layout/recuperar-contrasena/': typeof AuthLayoutRecuperarContrasenaIndexLazyRoute
  '/_authenticated/_layout/portal/dashboard/': typeof AuthenticatedLayoutPortalDashboardIndexRoute
  '/_authenticated/_layout/portal/notificaciones/': typeof AuthenticatedLayoutPortalNotificacionesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/portal/politicas-de-privacidad'
    | '/portal/terminos-condiciones'
    | '/email/resend'
    | '/iniciar-sesion'
    | '/recuperar-contrasena'
    | '/registrarme'
    | '/verify-email'
    | '/email/verify/$token'
    | '/recuperar-contrasena/nueva-contrasena'
    | '/mis-datos/'
    | '/recuperar-contrasena/'
    | '/portal/dashboard/'
    | '/portal/notificaciones/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/portal/politicas-de-privacidad'
    | '/portal/terminos-condiciones'
    | '/email/resend'
    | '/iniciar-sesion'
    | '/registrarme'
    | '/verify-email'
    | '/email/verify/$token'
    | '/recuperar-contrasena/nueva-contrasena'
    | '/mis-datos'
    | '/recuperar-contrasena'
    | '/portal/dashboard'
    | '/portal/notificaciones'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_authenticated'
    | '/_authenticated/_layout'
    | '/portal/politicas-de-privacidad'
    | '/portal/terminos-condiciones'
    | '/_auth/_layout'
    | '/__email/email/resend'
    | '/_auth/_layout/iniciar-sesion'
    | '/_auth/_layout/recuperar-contrasena'
    | '/_auth/_layout/registrarme'
    | '/_auth/_layout/verify-email'
    | '/__email/email/verify/$token'
    | '/_auth/_layout/recuperar-contrasena/nueva-contrasena'
    | '/_authenticated/_layout/mis-datos/'
    | '/_auth/_layout/recuperar-contrasena/'
    | '/_authenticated/_layout/portal/dashboard/'
    | '/_authenticated/_layout/portal/notificaciones/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PortalPoliticasDePrivacidadRoute: typeof PortalPoliticasDePrivacidadRoute
  PortalTerminosCondicionesRoute: typeof PortalTerminosCondicionesRoute
  _emailEmailResendLazyRoute: typeof _emailEmailResendLazyRoute
  _emailEmailVerifyTokenLazyRoute: typeof _emailEmailVerifyTokenLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/_layout': {
      id: '/_auth/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/portal/terminos-condiciones': {
      id: '/portal/terminos-condiciones'
      path: '/portal/terminos-condiciones'
      fullPath: '/portal/terminos-condiciones'
      preLoaderRoute: typeof PortalTerminosCondicionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/politicas-de-privacidad': {
      id: '/portal/politicas-de-privacidad'
      path: '/portal/politicas-de-privacidad'
      fullPath: '/portal/politicas-de-privacidad'
      preLoaderRoute: typeof PortalPoliticasDePrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_layout': {
      id: '/_authenticated/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedLayoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_auth/_layout/verify-email': {
      id: '/_auth/_layout/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthLayoutVerifyEmailLazyRouteImport
      parentRoute: typeof AuthLayoutLazyRoute
    }
    '/_auth/_layout/registrarme': {
      id: '/_auth/_layout/registrarme'
      path: '/registrarme'
      fullPath: '/registrarme'
      preLoaderRoute: typeof AuthLayoutRegistrarmeLazyRouteImport
      parentRoute: typeof AuthLayoutLazyRoute
    }
    '/_auth/_layout/recuperar-contrasena': {
      id: '/_auth/_layout/recuperar-contrasena'
      path: '/recuperar-contrasena'
      fullPath: '/recuperar-contrasena'
      preLoaderRoute: typeof AuthLayoutRecuperarContrasenaLazyRouteImport
      parentRoute: typeof AuthLayoutLazyRoute
    }
    '/_auth/_layout/iniciar-sesion': {
      id: '/_auth/_layout/iniciar-sesion'
      path: '/iniciar-sesion'
      fullPath: '/iniciar-sesion'
      preLoaderRoute: typeof AuthLayoutIniciarSesionLazyRouteImport
      parentRoute: typeof AuthLayoutLazyRoute
    }
    '/__email/email/resend': {
      id: '/__email/email/resend'
      path: '/email/resend'
      fullPath: '/email/resend'
      preLoaderRoute: typeof _emailEmailResendLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/_layout/recuperar-contrasena/': {
      id: '/_auth/_layout/recuperar-contrasena/'
      path: '/'
      fullPath: '/recuperar-contrasena/'
      preLoaderRoute: typeof AuthLayoutRecuperarContrasenaIndexLazyRouteImport
      parentRoute: typeof AuthLayoutRecuperarContrasenaLazyRoute
    }
    '/_authenticated/_layout/mis-datos/': {
      id: '/_authenticated/_layout/mis-datos/'
      path: '/mis-datos'
      fullPath: '/mis-datos/'
      preLoaderRoute: typeof AuthenticatedLayoutMisDatosIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_auth/_layout/recuperar-contrasena/nueva-contrasena': {
      id: '/_auth/_layout/recuperar-contrasena/nueva-contrasena'
      path: '/nueva-contrasena'
      fullPath: '/recuperar-contrasena/nueva-contrasena'
      preLoaderRoute: typeof AuthLayoutRecuperarContrasenaNuevaContrasenaLazyRouteImport
      parentRoute: typeof AuthLayoutRecuperarContrasenaLazyRoute
    }
    '/__email/email/verify/$token': {
      id: '/__email/email/verify/$token'
      path: '/email/verify/$token'
      fullPath: '/email/verify/$token'
      preLoaderRoute: typeof _emailEmailVerifyTokenLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_layout/portal/notificaciones/': {
      id: '/_authenticated/_layout/portal/notificaciones/'
      path: '/portal/notificaciones'
      fullPath: '/portal/notificaciones/'
      preLoaderRoute: typeof AuthenticatedLayoutPortalNotificacionesIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/_layout/portal/dashboard/': {
      id: '/_authenticated/_layout/portal/dashboard/'
      path: '/portal/dashboard'
      fullPath: '/portal/dashboard/'
      preLoaderRoute: typeof AuthenticatedLayoutPortalDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
  }
}

declare module './routes/index' {
  const createFileRoute: CreateFileRoute<
    '/',
    FileRoutesByPath['/']['parentRoute'],
    FileRoutesByPath['/']['id'],
    FileRoutesByPath['/']['path'],
    FileRoutesByPath['/']['fullPath']
  >
}
declare module './routes/_auth' {
  const createFileRoute: CreateFileRoute<
    '/_auth',
    FileRoutesByPath['/_auth']['parentRoute'],
    FileRoutesByPath['/_auth']['id'],
    FileRoutesByPath['/_auth']['path'],
    FileRoutesByPath['/_auth']['fullPath']
  >
}
declare module './routes/_authenticated' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated',
    FileRoutesByPath['/_authenticated']['parentRoute'],
    FileRoutesByPath['/_authenticated']['id'],
    FileRoutesByPath['/_authenticated']['path'],
    FileRoutesByPath['/_authenticated']['fullPath']
  >
}
declare module './routes/_authenticated/_layout' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/_layout',
    FileRoutesByPath['/_authenticated/_layout']['parentRoute'],
    FileRoutesByPath['/_authenticated/_layout']['id'],
    FileRoutesByPath['/_authenticated/_layout']['path'],
    FileRoutesByPath['/_authenticated/_layout']['fullPath']
  >
}
declare module './routes/portal/politicas-de-privacidad' {
  const createFileRoute: CreateFileRoute<
    '/portal/politicas-de-privacidad',
    FileRoutesByPath['/portal/politicas-de-privacidad']['parentRoute'],
    FileRoutesByPath['/portal/politicas-de-privacidad']['id'],
    FileRoutesByPath['/portal/politicas-de-privacidad']['path'],
    FileRoutesByPath['/portal/politicas-de-privacidad']['fullPath']
  >
}
declare module './routes/portal/terminos-condiciones' {
  const createFileRoute: CreateFileRoute<
    '/portal/terminos-condiciones',
    FileRoutesByPath['/portal/terminos-condiciones']['parentRoute'],
    FileRoutesByPath['/portal/terminos-condiciones']['id'],
    FileRoutesByPath['/portal/terminos-condiciones']['path'],
    FileRoutesByPath['/portal/terminos-condiciones']['fullPath']
  >
}
declare module './routes/_auth/_layout.lazy' {
  const createLazyFileRoute: CreateLazyFileRoute<
    FileRoutesByPath['/_auth/_layout']['preLoaderRoute']
  >
}
declare module './routes/__email/email.resend.lazy' {
  const createLazyFileRoute: CreateLazyFileRoute<
    FileRoutesByPath['/__email/email/resend']['preLoaderRoute']
  >
}
declare module './routes/_auth/_layout/iniciar-sesion.lazy' {
  const createLazyFileRoute: CreateLazyFileRoute<
    FileRoutesByPath['/_auth/_layout/iniciar-sesion']['preLoaderRoute']
  >
}
declare module './routes/_auth/_layout/recuperar-contrasena.lazy' {
  const createLazyFileRoute: CreateLazyFileRoute<
    FileRoutesByPath['/_auth/_layout/recuperar-contrasena']['preLoaderRoute']
  >
}
declare module './routes/_auth/_layout/registrarme.lazy' {
  const createLazyFileRoute: CreateLazyFileRoute<
    FileRoutesByPath['/_auth/_layout/registrarme']['preLoaderRoute']
  >
}
declare module './routes/_auth/_layout/verify-email.lazy' {
  const createLazyFileRoute: CreateLazyFileRoute<
    FileRoutesByPath['/_auth/_layout/verify-email']['preLoaderRoute']
  >
}
declare module './routes/__email/email.verify.$token.lazy' {
  const createLazyFileRoute: CreateLazyFileRoute<
    FileRoutesByPath['/__email/email/verify/$token']['preLoaderRoute']
  >
}
declare module './routes/_auth/_layout/recuperar-contrasena/nueva-contrasena.lazy' {
  const createLazyFileRoute: CreateLazyFileRoute<
    FileRoutesByPath['/_auth/_layout/recuperar-contrasena/nueva-contrasena']['preLoaderRoute']
  >
}
declare module './routes/_authenticated/_layout/mis-datos/index' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/_layout/mis-datos/',
    FileRoutesByPath['/_authenticated/_layout/mis-datos/']['parentRoute'],
    FileRoutesByPath['/_authenticated/_layout/mis-datos/']['id'],
    FileRoutesByPath['/_authenticated/_layout/mis-datos/']['path'],
    FileRoutesByPath['/_authenticated/_layout/mis-datos/']['fullPath']
  >
}
declare module './routes/_auth/_layout/recuperar-contrasena/index.lazy' {
  const createLazyFileRoute: CreateLazyFileRoute<
    FileRoutesByPath['/_auth/_layout/recuperar-contrasena/']['preLoaderRoute']
  >
}
declare module './routes/_authenticated/_layout/portal/dashboard/index' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/_layout/portal/dashboard/',
    FileRoutesByPath['/_authenticated/_layout/portal/dashboard/']['parentRoute'],
    FileRoutesByPath['/_authenticated/_layout/portal/dashboard/']['id'],
    FileRoutesByPath['/_authenticated/_layout/portal/dashboard/']['path'],
    FileRoutesByPath['/_authenticated/_layout/portal/dashboard/']['fullPath']
  >
}
declare module './routes/_authenticated/_layout/portal/notificaciones/index' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/_layout/portal/notificaciones/',
    FileRoutesByPath['/_authenticated/_layout/portal/notificaciones/']['parentRoute'],
    FileRoutesByPath['/_authenticated/_layout/portal/notificaciones/']['id'],
    FileRoutesByPath['/_authenticated/_layout/portal/notificaciones/']['path'],
    FileRoutesByPath['/_authenticated/_layout/portal/notificaciones/']['fullPath']
  >
}

interface AuthLayoutRecuperarContrasenaLazyRouteChildren {
  AuthLayoutRecuperarContrasenaNuevaContrasenaLazyRoute: typeof AuthLayoutRecuperarContrasenaNuevaContrasenaLazyRoute
  AuthLayoutRecuperarContrasenaIndexLazyRoute: typeof AuthLayoutRecuperarContrasenaIndexLazyRoute
}

const AuthLayoutRecuperarContrasenaLazyRouteChildren: AuthLayoutRecuperarContrasenaLazyRouteChildren =
  {
    AuthLayoutRecuperarContrasenaNuevaContrasenaLazyRoute:
      AuthLayoutRecuperarContrasenaNuevaContrasenaLazyRoute,
    AuthLayoutRecuperarContrasenaIndexLazyRoute:
      AuthLayoutRecuperarContrasenaIndexLazyRoute,
  }

const AuthLayoutRecuperarContrasenaLazyRouteWithChildren =
  AuthLayoutRecuperarContrasenaLazyRoute._addFileChildren(
    AuthLayoutRecuperarContrasenaLazyRouteChildren,
  )

interface AuthLayoutLazyRouteChildren {
  AuthLayoutIniciarSesionLazyRoute: typeof AuthLayoutIniciarSesionLazyRoute
  AuthLayoutRecuperarContrasenaLazyRoute: typeof AuthLayoutRecuperarContrasenaLazyRouteWithChildren
  AuthLayoutRegistrarmeLazyRoute: typeof AuthLayoutRegistrarmeLazyRoute
  AuthLayoutVerifyEmailLazyRoute: typeof AuthLayoutVerifyEmailLazyRoute
}

const AuthLayoutLazyRouteChildren: AuthLayoutLazyRouteChildren = {
  AuthLayoutIniciarSesionLazyRoute: AuthLayoutIniciarSesionLazyRoute,
  AuthLayoutRecuperarContrasenaLazyRoute:
    AuthLayoutRecuperarContrasenaLazyRouteWithChildren,
  AuthLayoutRegistrarmeLazyRoute: AuthLayoutRegistrarmeLazyRoute,
  AuthLayoutVerifyEmailLazyRoute: AuthLayoutVerifyEmailLazyRoute,
}

const AuthLayoutLazyRouteWithChildren = AuthLayoutLazyRoute._addFileChildren(
  AuthLayoutLazyRouteChildren,
)

interface AuthRouteChildren {
  AuthLayoutLazyRoute: typeof AuthLayoutLazyRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLayoutLazyRoute: AuthLayoutLazyRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedLayoutRouteChildren {
  AuthenticatedLayoutMisDatosIndexRoute: typeof AuthenticatedLayoutMisDatosIndexRoute
  AuthenticatedLayoutPortalDashboardIndexRoute: typeof AuthenticatedLayoutPortalDashboardIndexRoute
  AuthenticatedLayoutPortalNotificacionesIndexRoute: typeof AuthenticatedLayoutPortalNotificacionesIndexRoute
}

const AuthenticatedLayoutRouteChildren: AuthenticatedLayoutRouteChildren = {
  AuthenticatedLayoutMisDatosIndexRoute: AuthenticatedLayoutMisDatosIndexRoute,
  AuthenticatedLayoutPortalDashboardIndexRoute:
    AuthenticatedLayoutPortalDashboardIndexRoute,
  AuthenticatedLayoutPortalNotificacionesIndexRoute:
    AuthenticatedLayoutPortalNotificacionesIndexRoute,
}

const AuthenticatedLayoutRouteWithChildren =
  AuthenticatedLayoutRoute._addFileChildren(AuthenticatedLayoutRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedLayoutRoute: typeof AuthenticatedLayoutRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedLayoutRoute: AuthenticatedLayoutRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PortalPoliticasDePrivacidadRoute: PortalPoliticasDePrivacidadRoute,
  PortalTerminosCondicionesRoute: PortalTerminosCondicionesRoute,
  _emailEmailResendLazyRoute: _emailEmailResendLazyRoute,
  _emailEmailVerifyTokenLazyRoute: _emailEmailVerifyTokenLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
